[package]
name = "gh-updates"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
chrono = "0.4.43"
octocrab = "0.49.5"
tokio = { version = "1.49.0", features = ["rt-multi-thread", "macros"] }
